---
- name: Installation
  hosts: all
  become: true

  tasks:
  - name: Install git from package repositories
    ansible.builtin.package:
      name: git
      state: present
  - name: Git checkout from github of OpenPLC
    ansible.builtin.git:
      repo: https://github.com/thiagoralves/OpenPLC_v3.git
      dest: /home/vagrant/OpenPLC_v3
  - name: Execute OpenPLC's installation script
    ansible.builtin.shell: 
      cmd: ./install.sh linux
      executable: /usr/bin/bash
      chdir: /home/vagrant/OpenPLC_v3
  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot: