---
- name: Install linux dependencies
  ansible.builtin.package:
    name:
      - build-essential
      - pkg-config
      - bison
      - flex
      - autoconf
      - automake
      - libtool
      - make
      - git
      - python2.7
      - sqlite3
      - cmake
      - curl
      - python3
      - python3-pip
    state: present
- name: Download pip2
  ansible.builtin.get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    # destination directory must exist
    dest: "{{ working_directory }}/get-pip.py"
    mode: 0644
    force: true
- name: Install pip2
  ansible.builtin.command:
    cmd: python2.7 '{{ working_directory }}/get-pip.py'
- name: Remove file get-pip.py (pip2)
  ansible.builtin.file:
    path: "{{ working_directory }}/get-pip.py"
    state: absent
- name: Install python2 dependencies
  ansible.builtin.pip:
    name:
      - flask
      - flask-login
      - pyserial
      - pymodbus
    executable: pip2
- name: Install python3 dependencies
  ansible.builtin.pip:
    name:
      - pymodbus
    executable: pip3
- name: Git checkout from github of OpenPLC
  ansible.builtin.git:
    repo: https://github.com/thiagoralves/OpenPLC_v3.git
    dest: "{{ working_directory }}/OpenPLC_v3"
    version: da2c9674b6ac866bd0bc4133d8023958db5c0be0
- name: Execute OpenPLC's installation script # noqa command-instead-of-shell
# The installation script (and the other scripts it calls) uses pipelines and
# other shell functionalities, so it's not possible to use the command module
  ansible.builtin.shell:
    cmd: ./install.sh custom
    chdir: "{{ working_directory }}/OpenPLC_v3"
- name: Template the openplc.service file to the remote host
  ansible.builtin.template:
    src: openplc.service
    dest: /lib/systemd/system/
    mode: 0644
- name: Enable and start openplc service
  ansible.builtin.systemd:
    name: openplc.service
    state: started
    enabled: true
    daemon_reload: true
